EXP_NAME: Random
SEED: 223

DATASET:
  datadir: /datasets
  dataname: CIFAR10
  num_classes: 10
  batch_size: 128
  test_batch_size: 256
  num_workers: 12
  
OPTIMIZER:
  opt_name: SGD
  lr: 0.1

TRAIN:
  epochs: 100
  grad_accum_steps: 1
  mixed_precision: 'fp16'
  log_interval: 10
  ckpdir: null
  use_wandb: true

MODEL:
  modelname: resnet18

AL: # active learning
  strategy: RandomSampling # RandomSampling, LeastConfidence, MarginSampling, EntropySampling
  n_start: 5000 # start samples for intial training
  n_query: 500 # qeury samples for labeling
  n_end: 30000  # end samples for final training

RESULT:
  savedir: ./results