EXP_NAME: EntropySampling-ResNet18-CIFAR100
SEED: 223

DATASET:
  datadir: /datasets
  dataname: CIFAR100
  num_classes: 100
  batch_size: 128
  num_workers: 12
  
OPTIMIZER:
  opt_name: SGD
  lr: 0.1

TRAIN:
  epochs: 100
  grad_accum_steps: 1
  mixed_precision: 'fp16'
  log_interval: 10
  ckpdir: null
  use_wandb: true

AL: # active learning
  strategy: EntropySampling # Random, LeastConfidence, MarginSampling, EntropySampling
  start_ratio: 0.1 # start sample ratio for intial training
  query_ratio: 0.01 # qeury sample ratio for labeling
  end_ratio: 0.3  # end sample ratio for final training

RESULT:
  savedir: ./results/CIFAR100